#!/usr/bin/env python3
"""Regenerate INDEX.md from the frontmatter of every prompt in prompts/.

Run from the repo root:
    python scripts/update_index.py

Writes INDEX.md at the repo root. Safe to run repeatedly; it overwrites the file.
Named for its usual job: on the first run it creates INDEX.md, and on every run
after that it updates it.

The index orders prompts so the curation signal comes first: 'proven' prompts,
which the curation crew has granted, are listed at the top, then 'reviewed', then
'draft'. Deprecated prompts sit in a separate section at the foot of the file.
"""

from __future__ import annotations

import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("This script needs PyYAML. Install it with: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
PROMPTS_DIR = ROOT / "prompts"
INDEX_PATH = ROOT / "INDEX.md"

# Lower number sorts higher in the listing.
STATUS_ORDER = {"proven": 0, "reviewed": 1, "draft": 2, "deprecated": 9}


def split_frontmatter(text: str):
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    return parts[1]


def load_prompts():
    """Return a list of metadata dicts, one per readable prompt file."""
    prompts = []
    for path in sorted(PROMPTS_DIR.glob("*.md")):
        block = split_frontmatter(path.read_text(encoding="utf-8"))
        if block is None:
            continue
        try:
            meta = yaml.safe_load(block) or {}
        except yaml.YAMLError:
            continue
        if not isinstance(meta, dict) or "id" not in meta:
            continue
        meta["_filename"] = path.name
        prompts.append(meta)
    return prompts


def cell(value: str) -> str:
    """Make a value safe to place inside a Markdown table cell."""
    return str(value).replace("|", r"\|").replace("\n", " ").strip()


def as_list(value):
    if isinstance(value, list):
        return value
    if value in (None, ""):
        return []
    return [value]


def sort_key(meta: dict):
    status_rank = STATUS_ORDER.get(meta.get("status"), 5)
    rank = meta.get("rank")
    rank = rank if isinstance(rank, int) else 9999
    return (status_rank, rank, str(meta.get("title", "")).lower())


def render(prompts) -> str:
    today = datetime.date.today().isoformat()
    active = [p for p in prompts if p.get("status") != "deprecated"]
    deprecated = [p for p in prompts if p.get("status") == "deprecated"]
    active.sort(key=sort_key)
    deprecated.sort(key=sort_key)

    lines = []
    lines.append("# Prompt index")
    lines.append("")
    lines.append(
        f"Generated by `scripts/update_index.py` on {today}. "
        "Do not edit by hand; your changes will be overwritten. "
        "Regenerate after adding or changing a prompt."
    )
    lines.append("")

    # Curation signal: proven prompts first, only shown when some exist.
    proven = [p for p in active if p.get("status") == "proven"]
    if proven:
        lines.append("## Proven prompts")
        lines.append("")
        lines.append("Granted by the curation crew as reliably useful.")
        lines.append("")
        for p in proven:
            lines.append(
                f"- [{cell(p.get('title'))}]"
                f"(prompts/{p['_filename']}) - {cell(p.get('purpose'))}"
            )
        lines.append("")

    # Full table of active prompts.
    lines.append("## All prompts")
    lines.append("")
    lines.append(f"{len(active)} active prompt(s).")
    lines.append("")
    lines.append("| Prompt | Purpose | Tags | Automation | Status |")
    lines.append("|--------|---------|------|------------|--------|")
    for p in active:
        title_link = f"[{cell(p.get('title'))}](prompts/{p['_filename']})"
        tags = ", ".join(cell(t) for t in as_list(p.get("tags")))
        automation = cell(p.get("automation", "interactive"))
        status = cell(p.get("status", ""))
        lines.append(
            f"| {title_link} | {cell(p.get('purpose'))} | {tags} "
            f"| {automation} | {status} |"
        )
    lines.append("")

    # Browse by tag.
    tag_map: dict[str, list] = {}
    for p in active:
        for tag in as_list(p.get("tags")):
            tag_map.setdefault(str(tag), []).append(p)
    if tag_map:
        lines.append("## Browse by tag")
        lines.append("")
        for tag in sorted(tag_map):
            entries = sorted(tag_map[tag], key=sort_key)
            links = ", ".join(
                f"[{cell(p.get('title'))}](prompts/{p['_filename']})"
                for p in entries
            )
            lines.append(f"- **{cell(tag)}**: {links}")
        lines.append("")

    # Deprecated, kept in place for stable links and history.
    if deprecated:
        lines.append("## Deprecated")
        lines.append("")
        lines.append("Kept for reference and stable links. Do not use these.")
        lines.append("")
        for p in deprecated:
            lines.append(
                f"- [{cell(p.get('title'))}]"
                f"(prompts/{p['_filename']}) - {cell(p.get('purpose'))}"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    if not PROMPTS_DIR.is_dir():
        raise SystemExit(f"No prompts directory found at {PROMPTS_DIR}")

    prompts = load_prompts()
    INDEX_PATH.write_text(render(prompts), encoding="utf-8")

    proven = sum(1 for p in prompts if p.get("status") == "proven")
    deprecated = sum(1 for p in prompts if p.get("status") == "deprecated")
    print(
        f"Wrote {INDEX_PATH.name}: {len(prompts)} prompt(s) "
        f"({proven} proven, {deprecated} deprecated)."
    )


if __name__ == "__main__":
    main()
